### ISSUE TITLE
AttributeError: __mro__

### ISSUE THREAD

**Issue by multimeric** [pyapp-kit/fieldz#23]
* fieldz version: 0.0.2
* Python version: 3.10.13
* Operating System: MacOS 12.6

### Description

I was trying to use `griffe-fieldz` on my codebase, which uses a lot of type annotations. I noticed the below error, which I've now simplified into an MRE.

### What I Did

```python
import fieldz
from pydantic import BaseModel
from typing import Any

class Foo(BaseModel):
    foo: Any

fieldz.fields(Foo)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/fieldz/_functions.py", line 28, in fields
    fields = get_adapter(obj).fields(obj)
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/fieldz/adapters/_pydantic.py", line 173, in fields
    return tuple(_fields_v1(obj))
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/fieldz/adapters/_pydantic.py", line 100, in _fields_v1
    constraints=_constraints_v1(modelfield),
  File "/opt/anaconda3/envs/napari2/lib/python3.10/site-packages/fieldz/adapters/_pydantic.py", line 107, in _constraints_v1
    for subt in modelfield.type_.__mro__:
  File "/opt/anaconda3/envs/napari2/lib/python3.10/typing.py", line 375, in __getattr__
    raise AttributeError(item)
AttributeError: __mro__. Did you mean: '__or__'?
```

**Comment by multimeric** [comment]
Okay this is confused by the fact that Python 3.11 fixed this in the core language:

> Changed in version 3.11: [Any](https://docs.python.org/3/library/typing.html#typing.Any) can now be used as a base class. This can be useful for avoiding type checker errors with classes that can duck type anywhere or are highly dynamic.

[Source](https://docs.python.org/3/library/typing.html#the-any-type:~:text=Changed%20in%20version%203.11%3A%20Any%20can%20now%20be%20used%20as%20a%20base%20class.%20This%20can%20be%20useful%20for%20avoiding%20type%20checker%20errors%20with%20classes%20that%20can%20duck%20type%20anywhere%20or%20are%20highly%20dynamic.)

**Comment by multimeric** [comment]
A workaround is to use `typing_extensions.Any` instead of `typing.Any` in those old versions.

**Comment by multimeric** [comment]
On the other hand, `Union` and various other types like this are not wrapper by `typing_extensions`, so I can't see how to avoid this issue:

```
import fieldz
from pydantic import BaseModel
from typing import Union

class Foo(BaseModel):
    foo: Union[int, float]

fieldz.fields(Foo)
```
```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Users/milton.m/Programming/fieldz/src/fieldz/_functions.py", line 28, in fields
    fields = get_adapter(obj).fields(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milton.m/Programming/fieldz/src/fieldz/adapters/_pydantic.py", line 177, in fields
    return tuple(_fields_v1(obj))
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milton.m/Programming/fieldz/src/fieldz/adapters/_pydantic.py", line 104, in _fields_v1
    constraints=_constraints_v1(modelfield),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milton.m/Programming/fieldz/src/fieldz/adapters/_pydantic.py", line 111, in _constraints_v1
    for subt in modelfield.type_.__mro__:
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 1318, in __getattr__
    raise AttributeError(attr)
AttributeError: __mro__
```
